services:
  atomiq-monitor:
    build: /home/liam/docker/compose/atomiq-monitor
    container_name: atomiq-monitor
    restart: always
    env_file: /home/liam/docker/compose/atomiq-monitor/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
